# Generated by Django 4.0.2 on 2022-04-19 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LEC_RMSapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='back_board_exam',
            name='regular',
        ),
        migrations.AddField(
            model_name='back_board_exam',
            name='year_part',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='LEC_RMSapp.year_part'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='regular_board_exam',
            name='year_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LEC_RMSapp.year_part'),
        ),
    ]
